export {default as Jumbotron} from './jumbotron'
export {default as Accordeon} from './Accordeon'
export {default as Footer} from './footer'
export {default as OptForm } from './optIn'
export {default as Feature } from './feature'
export {default as Header } from './header'